### ISSUE TITLE
wrong lapis count

### ISSUE THREAD

**Issue by mamasch19** [JoeJoeTV/datapacks#1]
"readme.md" says veinmining needs 12 lapis lazuli. You actually need 16. 
@JoeJoeTV pls fix "readme.md" or recipe

Screenshots:
![image](https://github.com/JoeJoeTV/datapacks/raw/master/assets/images/spell_recipe_veinmining.gif)
![image](https://user-images.githubusercontent.com/51797687/59455055-b09b4780-8e13-11e9-8dce-cd3729ebd61c.png)

**Comment by JoeJoeTV** [comment]
Fixed in a69ab6f632e786692cc89022ba1a084b36f666e1
