### ISSUE TITLE
[Suggestion] Veinmining Sand

### ISSUE THREAD

**Issue by mamasch19** [JoeJoeTV/datapacks#3]
Add sand to veinminable blocks

**Comment by mamasch19** [comment]
+leaves

**Comment by JoeJoeTV** [comment]
> +leaves

Leaves are buggy and don't really work with vein mining, but I can add sand.

**Comment by JoeJoeTV** [comment]
Added with c48bc9f7c04bcae9f637c6c4bc0d222d87e55327
